# Generated by Django 5.0.3 on 2024-03-13 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name_of_poll')),
                ('opened', models.BooleanField(default=True, verbose_name='opened')),
            ],
        ),
    ]
